In [1]:
# 필요한 라이브러리를 불러옵니다.
import numpy as np

### 1. 값이 10~49인 numpy array를 만드세요

In [14]:
z = np.array(np.arange(10,50))
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 2. z를 반전하세요.

In [15]:
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 3. 반전시킨 z 매트릭스를 10 x 4 매트릭스로 바꾸세요.

In [16]:
z = z.reshape((10,4))
print(z)

[[49 48 47 46]
 [45 44 43 42]
 [41 40 39 38]
 [37 36 35 34]
 [33 32 31 30]
 [29 28 27 26]
 [25 24 23 22]
 [21 20 19 18]
 [17 16 15 14]
 [13 12 11 10]]


### 4. x에서 0이 아닌 요소의 색인을 찾아보세요.

In [18]:
x = np.array([5,6,8,0,1,0,7])
nz_idx = np.where(x != 0)
print(nz_idx)

(array([0, 1, 2, 4, 6]),)


### nan 값 이해하기



In [ ]:
print(np.nan == np.nan)
print(np.isnan(np.nan))

import math
print(0.3 == 3 * 0.1)
print(math.isclose(0.1 + 0.2, 0.3))

False
True
False
True


### 5. 12 x 12 매트릭스를 만들어 바둑판 패턴으로 0과 1을 채우세요

In [39]:
# https://jimmy-ai.tistory.com/93
x = np.zeros((12, 12))
print(x, end='\n\n')
### 슬라이싱 ###
x[0::2,1::2] = 1
x[1::2,0::2] = 1
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]


### 6. np.tile 을 이용해서 동일한 바둑판 배턴을 만들어보세요

In [45]:
x = np.tile([np.tile([0, 1],6), np.tile([1, 0],6)], (6,1))
print(x)

[[0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0]]


### 7. 1차원 배열이 x에서 값이 5~10인 요소를 0으로 바꾸세요

In [ ]:
x = np.array([2,5,3,8,3,34,23,7,10])
print(x)
### 필터링 ###
x[(x>=5) & (x<=10)] = 0
print(x)

[ 2  5  3  8  3 34 23  7 10]
[ 2  0  3  0  3 34 23  0  0]


### 8. 0에서 100 사이의 값으로 크기가 10인 1차원 array를 만드세요

In [49]:
# https://zephyrus1111.tistory.com/144
x = np.linspace(0,100,10)
print(x)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


### 9. np.allclose() 함수를 사용하여 2개의 array가 같은지를 확인해보세요

In [50]:
A = np.array([1e10,1e-8])
B = np.array([1.00001e10,1e-9])

equal = np.allclose(A,B)
print(equal)

True


### 10. 데카르트 좌표를 나타내는 랜덤 8 x 2 행렬을 고려하여 극좌표로 변환해보세요.

In [60]:
# 데카르트 좌표(Cartesian coordinates)는 일반적으로 직교 좌표계로,
# 2차원에서는 (x, y), 3차원에서는 (x, y, z)와 같은 형태로 나타내는 좌표 체계입니다.
# 반면 극좌표(Polar coordinates)는 원점에서의 거리(r)와 각도(θ)로 나타내는 다른 형태의 좌표 체계입니다.
# 데카르트 좌표를 극좌표로 변환하는 방법은 다음과 같습니다:
# (x, y) 좌표에서 원점까지의 거리 r을 계산합니다. 이 거리는 r = sqrt(x^2 + y^2)로 구할 수 있습니다.
# (x, y) 좌표에서 원점까지의 각도 θ를 계산합니다. 이 각도는 θ = atan2(y, x)로 구할 수 있습니다.

coord = np.random.random((10,2))
x, y = coord[:,0], coord[:,1]
r = np.sqrt(x**2+y**2)
theta = np.arctan2(y,x)
ploar_coord = np.concatenate([r[:,np.newaxis], theta[:,np.newaxis]],axis=1)
print(ploar_coord)

[[1.0063456  0.43560201]
 [0.86359014 0.37954386]
 [0.76043302 0.96074994]
 [0.87156004 1.16470145]
 [0.85645216 0.69891386]
 [0.40681329 0.21091306]
 [1.25146791 0.87844335]
 [0.79967831 0.41136328]
 [0.81181119 0.78021585]
 [1.14963217 0.9199794 ]]
